name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          version: 14.x
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.0
      - name: Install Dependencies & Build
        run: |
          pnpm install  --frozen-lockfile
          pnpm build
      - name: Test
        run: pnpm test
